const EmployeeDB = [
    {
      employeeName: "Alice",
      employeeId: "E001",
      joiningDate: "2022-01-01",
      Role: "Developer",
      Status: "Active",
      Experience: "2 years",
    },
    {
      employeeName: "Bob",
      employeeId: "E002",
      joiningDate: "2021-05-12",
      Role: "Designer",
      Status: "Inactive",
      Experience: "3 years",
    },
    {
      employeeName: "Charlie",
      employeeId: "E003",
      joiningDate: "2023-03-15",
      Role: "Tester",
      Status: "Probation",
      Experience: "1 year",
    },
    {
      employeeName: "Diana",
      employeeId: "E004",
      joiningDate: "2020-11-05",
      Role: "Manager",
      Status: "Active",
      Experience: "5 years",
    },
    {
      employeeName: "Ethan",
      employeeId: "E005",
      joiningDate: "2024-01-10",
      Role: "Intern",
      Status: "Probation",
      Experience: "6 months",
    },
    {
      employeeName: "Fiona",
      employeeId: "E006",
      joiningDate: "2022-07-20",
      Role: "Developer",
      Status: "Active",
      Experience: "2 years",
    },
    {
      employeeName: "George",
      employeeId: "E007",
      joiningDate: "2019-02-25",
      Role: "Support",
      Status: "Inactive",
      Experience: "6 years",
    },
    {
      employeeName: "Hannah",
      employeeId: "E008",
      joiningDate: "2023-09-01",
      Role: "HR",
      Status: "Active",
      Experience: "1 year",
    },
    {
      employeeName: "Ivan",
      employeeId: "E009",
      joiningDate: "2021-06-30",
      Role: "Tester",
      Status: "Probation",
      Experience: "2.5 years",
    },
    {
      employeeName: "Julia",
      employeeId: "E010",
      joiningDate: "2020-12-12",
      Role: "Manager",
      Status: "Active",
      Experience: "4 years",
    }
  ];
  export default EmployeeDB
